### ISSUE TITLE
UI Character set disappears when wild touching

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox02-firmware#155] opened 2019-10-07 11:53 UTC
Touching wildly around, especially top center and right together with bottom right
might break the UI and characters disappear.

![65694228-c86ea280-e075-11e9-90be-8b04216a4a31](https://user-images.githubusercontent.com/546900/66309394-d50eb880-e909-11e9-8540-a34db8c6d660.gif)

might be related to #92 ?

**Comment by NickeZ** [comment] 2020-01-07 18:29
Can you still reproduce this on the latest firmware? I believe I have a fix, but I cannot reproduce the problem anymore.

**Comment by thisconnect** [comment] 2020-01-07 20:34
@NickeZ you are right, it is much harder almost impossible now to reproduce as I described.

I did manage doing it when touching on the top middle/right first followed by bottom middle/right.

Updated step to reproduce:
touching the ABC (topmiddle) that rotates the ABC, then immediately touching top/right will reproduce it again. 

FYI I can't see the animation of the ABC rotation but I strongly believe the bug only works if it rotated. Maybe touching the bottom was never important

BTW: the UI still works, 
i.e. the delete touch still works.

this is Firmware 5.0.0 and App 4.16.0

❤️ for looking into this. and as said it is already way better!

**Comment by thisconnect** [comment] 2020-01-07 20:35
let me know if you understood my description, I could phrase it differently if you want or try to record another video.

**Comment by thisconnect** [comment] 2020-01-07 20:41
As it is still pretty hard to reproduce it is also fine by me if you wontfix this, feel free to close or lowprio

**Comment by NickeZ** [comment] 2020-01-08 13:32
> touching the ABC (topmiddle) that rotates the ABC, then immediately touching top/right will reproduce it again.

I tried to do this for several minutes and couldn't reproduce it. Maybe you could shoot a video of it? It sounds like we have a race condition that is going to be quite hard to solve unless I can reproduce it.

**Comment by NickeZ** [comment] 2020-02-18 21:07
This was fixed in https://github.com/digitalbitbox/bitbox02-firmware/pull/278 and is part of the 6.0.0 firmware release. Thank you for your patience!

**Closed by NickeZ** 2020-02-18 21:07 UTC
